version: '3.8'
services:
  order:
    build: ./order_service
    container_name: order_service
    ports:
      - "5000:5000"
    environment:
      - INVENTORY_URL=http://inventory:5001
      - NOTIFICATION_URL=http://notification:5002

  inventory:
    build: ./inventory_service
    container_name: inventory_service
    ports:
      - "5001:5001"

  notification:
    build: ./notification_service
    container_name: notification_service
    ports:
      - "5002:5002"
